package com.smartcampus.api.model;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    ACCOUNT_INVITED,
    ACCOUNT_SETUP_COMPLETED,
    USER_CREATED,
    USER_DELETED,
    USER_ROLE_CHANGED,
    OAUTH_LINKED,
    OAUTH_SIGNUP,
    OAUTH_BLOCKED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    TICKET_STATUS_CHANGED,
    TICKET_ASSIGNED
}
