spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: smart-campus-api
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_campus
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET_KEY}
    expiration-ms: 900000  # 15 minutes
    refresh-expiration-ms: 604800000 # 7 days
  oauth2:
    redirect-uri: http://localhost:5173/oauth2/redirect
  frontend:
    url: http://localhost:5173
